version: "3"

services:
    db:
        image: mongo
        ports:
            - "27117:27017"
        volumes:
            - ./data/db:/data/db
    redis:
        image: redis
    app:
        build: .
        volumes:
            - ./config.json:/app/config.json
        ports:
            - 127.0.0.1:32457:5000
        depends_on:
            - db
            - redis
